### ISSUE TITLE
/command integration doc doesn't mention arguments set when triggered by chat

### ISSUE THREAD

**Issue by artyom** [Doist/twist-api#14]
Documentation for slash-command integrations does not mention arguments received when it's triggered from conversations (chats). Namely these fields are missing from example:

* `conversation_title`
* `conversation_id`
* `message_id`

Also `thread_*`, `channel_*` and `comment_id` arguments are not sent in such case.

**Comment by PaulHalliday** [comment]
I've updated this as requested. Thanks Artyom! 👍
