### ISSUE TITLE
Is there any way to build extensions for twist ?

### ISSUE THREAD

**Issue by tornikegomareli** [Doist/twist-api#19]
We want to make Github extension for our channels and threads,
to notify all repository state changes, like slack has.

Is there any way to do this ? or there are no such thing "extensions" for the twist?

**Comment by rohitpaulk** [comment]
Hey @tornikegomareli, not sure if you've found this already - but we do have a GitHub integration for Twist. Here's an article that describes what it does and how to set it up: https://twist.zendesk.com/hc/en-us/articles/115003653629-Connect-GitHub-to-Twist

**Comment by tornikegomareli** [comment]
Yes I have already found it. Thank you for your fast response. Twist is
great ! Keep going !
