### ISSUE TITLE
Looks like V3 documentation is not correct

### ISSUE THREAD

**Issue by morajabi** [Doist/twist-api#20]
API responses are different from what's documented for v3, I assume it's a copy of v2 for now? 

As an example, I don't receive snooze information as part of user object (`/v3/workspace_users/` or `/v3/workspaces/get_user_by_id`), I guess you have added a new endpoint for those details which isn't documented. 

If there's anything I can help to at least have the correct urls, please let me know! 

\cc @henningmu

**Comment by henningmu** [comment]
@morajabi IIRC the snooze information are only available for the session user. No one else should care about these (I know we "leaked" them in v2).
However, you get the away_mode setting for every user if that helps in your case :)
