### ISSUE TITLE
Improve avatars upload endpoint argument documentation

### ISSUE THREAD

**Issue by artyom** [Doist/twist-api#8]
Update avatar endpoint description at https://developer.twistapp.com/v2/#update-avatar has the following argument list:

Name | Required | Description
-- | -- | --
image String | Yes | The file name of the image to upload

along with this curl example:

    curl -X POST https://api.twistapp.com/api/v2/users/update_avatar \
      -H "Authorization: Bearer 9b1bf97783c1ad5593dee12f3019079dbd3042cf" \ 
      -F image=@avatar.jpg

I think we need to re-word this a bit differently to make it more clear how the form is handled by the server — that `image` **form field is for file contents itself, not the name**. The comment to `image` argument — *The file name of the image to upload* — is misleading here, it only applies to the particular curl call example, not to the API endpoint.

It's better shown when compared to another endpoint, like the one to update password: https://developer.twistapp.com/v2/#update-password

Update password endpoint is documented to accept single string argument `new_password` — and indeed most client implementations would send it to the server as `application/x-www-form-urlencoded` form in `new_password=newsecret` key-value pair.

Avatar update endpoint differs because it expects form to be a `multipart/form-data` (because we uploading binary data) and so server is looking for **the content of uploaded file** in the `image` form field, not the name (and the value is not a string). Also it's worth mentioning here whether or not filename is used by the server at all, since it [may be omitted at all in cases when unused](https://tools.ietf.org/html/rfc7578#section-4.2).

Probably something like this would be enough:

> `image` — avatar image uploaded as `multipart/form-data`.

**Comment by PotHix** [comment]
Good catch @artyom! It's was fixed on d8977e1a453b11ea00257302f81f10b8c6da95e1
